[package]
name = "remap-path-prefix"
description = """
Computes the rustc flag `--remap-path-prefix` arguments that are needed
to make the build artifacts reproducible.
"""
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
home = "0.5.11"
