[package]
name = "abstract-tun"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
tokio = { version = "1", features = [ "rt", "sync", "io-util", "net", "time", "fs", "macros" ] }
async-trait = "0.1"
x25519-dalek = { version = "2", features = [ "reusable_secrets", "static_secrets" ] }
# boringtun = { git = "https://github.com/mullvad/boringtun", rev = "44fffd131212d08febb3799bfc9f951fd3893c4c", default-features = false }
boringtun = { path = "../../../src/boringtun/boringtun", default-features = false }
libc ="0.2"

# nix = { version = "0.25", default-features = false, features = [
#     "time",
# ] }

[target.'cfg(target_os = "ios")'.dependencies]
nix = { version = "0.27", default-features = false, features = [
    "time"
] }





[target.'cfg(target_os = "macos")'.dependencies]
env_logger = "0.10"
tun = "0.5.1"
base64 = "0.21"
nix = "0.26"
libc = "0.2"

[build-dependencies]
cbindgen = { version = "0.24.3", default-features = false }

[lib]
crate-type = [ "rlib", "staticlib" ]
bench = false
