---
name: Android - Gradle verification task
on:
  workflow_dispatch:
  push:

permissions: {}

jobs:
  run-gradle-verification-tests:
    name: Run gradle verification tests
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.prepare.outputs.container_image }}
    strategy:
      fail-fast: false
      matrix:
        gradle-task-assemble: [assemble, '']
        gradle-task-lint: [lint, '']
        gradle-task-unit-test: [compileDebugUnitTestKotlin, '']
        gradle-task-assemble-test: [assembleAndroidTest, '']
    steps:
      # Fix for HOME path overridden by GH runners when building in containers, see:
      # https://github.com/actions/runner/issues/863
      - name: Fix HOME path
        run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create verification file
        run: |
          cd android
          ./gradlew -M sha256 ${{ matrix.gradle-task-assemble }} ${{ matrix.gradle-task-lint }} ${{ matrix.gradle-task-unit-test }} ${{ matrix.gradle-task-assemble-test }}
          sha256 gradle/verification-metadata.xml

      - name: Upload verification file
        uses: actions/upload-artifact@v4
        with:
          name: verification-file-${{ matrix.gradle-task-assemble }}-${{ matrix.gradle-task-lint }}-${{ matrix.gradle-task-unit-test }}-${{ matrix.gradle-task-assemble-test }}
          path: android/gradle/verification-metadata.xml
          if-no-files-found: error
          retention-days: 7